### ISSUE TITLE
AttributeError: 'Annotation' object has no property 'text_from_points'

### ISSUE THREAD

**Issue by zhoujj2013** [loosolab/TOBIAS#221]
When we run  BINDetect, we come across this problem:

2023-06-06 23:11:56 (20600) [INFO]      Processing scanned TFBS individually
2023-06-06 23:11:56 (20600) [INFO]      Progress 0%
2023-06-06 23:11:56 (20600) [INFO]      Progress 8.3%
2023-06-06 23:11:56 (20600) [INFO]      Progress 66.7%
2023-06-06 23:11:57 (20600) [INFO]      Progress 100.0%
2023-06-06 23:11:57 (20600) [INFO]      Progress done!
2023-06-06 23:11:57 (20600) [INFO]      Concatenating results from subsets

2023-06-06 23:11:57 (20600) [INFO]      Writing all_bindetect files
2023-06-06 23:11:57 (20600) [INFO]      Creating BINDetect plot(s)
2023-06-06 23:11:57 (20600) [INFO]      - D3 / D7 (static plot)
Traceback (most recent call last):
  File "/home/zhoujj/anaconda2/envs/TOBIAS/bin/TOBIAS", line 8, in <module>
    sys.exit(main())
  File "/home/zhoujj/anaconda2/envs/TOBIAS/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)
  File "/home/zhoujj/anaconda2/envs/TOBIAS/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 819, in run_bindetect
    fig = plot_bindetect(motif_list, clustering, [cond1, cond2], args)
  File "/home/zhoujj/anaconda2/envs/TOBIAS/lib/python3.7/site-packages/tobias/tools/bindetect_functions.py", line 769, in plot_bindetect
    adjust_text(txts, ax=ax1, add_objects=[l], text_from_points=True, arrowprops=dict(arrowstyle='-', color='black', lw=0.5))  #, expand_text=(0.1,1.2), expand_objects=(0.1,0.1))
  File "/home/zhoujj/anaconda2/envs/TOBIAS/lib/python3.7/site-packages/adjustText/__init__.py", line 738, in adjust_text
    **kwargs
  File "/home/zhoujj/anaconda2/envs/TOBIAS/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 666, in annotate
    a = mtext.Annotation(text, xy, *args, **kwargs)
  File "/home/zhoujj/anaconda2/envs/TOBIAS/lib/python3.7/site-packages/matplotlib/text.py", line 1825, in __init__
    Text.__init__(self, x, y, text, **kwargs)
  File "/home/zhoujj/anaconda2/envs/TOBIAS/lib/python3.7/site-packages/matplotlib/text.py", line 160, in __init__
    self.update(kwargs)
  File "/home/zhoujj/anaconda2/envs/TOBIAS/lib/python3.7/site-packages/matplotlib/text.py", line 172, in update
    super().update(kwargs)
  File "/home/zhoujj/anaconda2/envs/TOBIAS/lib/python3.7/site-packages/matplotlib/artist.py", line 1067, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'Annotation' object has no property 'text_from_points'

Could you please help me with this?

Package           Version
----------------- --------
adjustText        0.8
args              0.1.0
biopython         1.81
boto3             1.26.147
botocore          1.29.147
clint             0.5.1
configs           3.0.3
coverage          7.2.7
cycler            0.11.0
Cython            0.29.35
docutils          0.20.1
fonttools         4.38.0
jmespath          1.0.1
joblib            1.2.0
kiwisolver        1.4.4
kneed             0.8.3
logomaker         0.8
mamba             0.11.2
matplotlib        3.5.3
MOODS-python      1.9.4.1
numpy             1.21.6
packaging         23.1
pandas            1.3.5
Pillow            9.5.0
pip               22.3.1
pybedtools        0.9.0
pyBigWig          0.3.22
pyfastaq          3.17.0
pyparsing         3.0.9
PyPDF2            3.0.1
pysam             0.21.0
python-dateutil   2.8.2
pytz              2023.3
PyYAML            6.0
reportlab         4.0.4
s3transfer        0.6.1
scikit-learn      1.0.2
scipy             1.2.0
seaborn           0.12.2
setuptools        65.5.1
six               1.16.0
statistics        1.0.3.5
svist4get         1.3.1
threadpoolctl     3.1.0
tobias            0.15.1
typing_extensions 4.6.3
urllib3           1.26.16
Wand              0.6.11
wheel             0.38.4
XlsxWriter        3.1.2

**Comment by msbentsen** [comment]
Hi, 

This is an error coming from another library - please downgrade `adjustText` to `<0.8` as also discussed here: https://github.com/loosolab/TOBIAS/issues/182#issuecomment-1400273409

That should solve the issue - otherwise please let us know, thanks!

**Comment by sngholee** [comment]
Hello,

I'm getting this issue w/ BINDetct. I've tried downgrading adjusttext but still get this below issue. This issue only arises when I do the time series, and running on single timepoints does not give any issues. I can't view the pdf output from the output when I try the time series. I'd appreciate any suggestions.


Code attempted:
`TOBIAS BINDetect --motifs ${JASPAR} --signals ${BIGWIGS}/Lo_{0,2,24,48,72}_REP2_score.bw $i  --genome \
        /public/groups/shariatilab/slee/RefGenomes/mm10.fa --peaks \
        /public/groups/shariatilab/slee/MEKiRound3/ATACSeq/redo/consensusPeaks/consensusPeaksBEDCoordsOnly.txt \
        --outdir ${OUTDIR}/ --time-series --cores 12`

The error message:
`Traceback (most recent call last):
  File "/public/home/slee393/miniconda3/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.16.1', 'console_scripts', 'TOBIAS')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/tobias-0.16.1-py3.11-linux-x86_64.egg/tobias/TOBIAS.py", line 162, in main
    args.func(args)
    ^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/tobias-0.16.1-py3.11-linux-x86_64.egg/tobias/tools/bindetect.py", line 819, in run_bindetect
    fig = plot_bindetect(motif_list, clustering, [cond1, cond2], args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/tobias-0.16.1-py3.11-linux-x86_64.egg/tobias/tools/bindetect_functions.py", line 773, in plot_bindetect
    adjust_text(txts, ax=ax1, add_objects=[l], text_from_points=True, arrowprops=dict(arrowstyle='-', color='black', lw=0.5))  #, expand_text=(0.1,1.2), expand_objects=(0.1,0.1))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/adjustText/__init__.py", line 730, in adjust_text
    ax.annotate(
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 711, in annotate
    a = mtext.Annotation(text, xy, xytext=xytext, xycoords=xycoords,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/text.py", line 1845, in __init__
    Text.__init__(self, x, y, text, **kwargs)
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/text.py", line 155, in __init__
    self.update(kwargs)
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/text.py", line 205, in update
    ret.extend(super().update(kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/artist.py", line 1209, in update
    return self._update_props(
           ^^^^^^^^^^^^^^^^^^^
  File "/public/home/slee393/miniconda3/lib/python3.11/site-packages/matplotlib/artist.py", line 1193, in _update_props
    raise AttributeError(
AttributeError: 'Annotation' object has no property 'text_from_points'`
